-- 案例1
-- 查询工资比7654高的所有员工信息
SELECT * FROM EMP WHERE SAL > (SELECT SAL FROM EMP WHERE EMPNO = 7654);

-- 查询和'SMITH', 'JONES'在同一部门，同一职位工作的员工
SELECT *
  FROM EMP
 WHERE (DEPTNO, JOB) IN (SELECT DEPTNO, JOB FROM EMP WHERE ENAME IN ('SMITH', 'JONES'))
   AND ENAME NOT IN ('SMITH', 'JONES');

-- =any
-- 查询和'SMITH', 'JONES'同一部门，同一职位工作的员工
SELECT *
  FROM EMP
 WHERE (DEPTNO, JOB) = ANY
 (SELECT DEPTNO, JOB FROM EMP WHERE ENAME IN ('SMITH', 'JONES'));
AND ENAME NOT IN('SMITH', 'JONES');

-- >any 只要大于子查询中的任意一个值即可
-- >ANY 保证大于子查询中的最小值
SELECT DEPTNO, MIN(SAL) FROM EMP GROUP BY DEPTNO;

SELECT ENAME, SAL, DEPTNO
  FROM EMP
 WHERE SAL > ANY (SELECT MIN(SAL) FROM EMP GROUP BY DEPTNO)
 ORDER BY SAL;

-- <ANY 只要小于子查询中的任意一个值即可
-- >ANY 保证小于子查询中的最大值

-- <ALL 比子查询的最小值小

-- from 子句中使用子查询
SELECT * FROM (SELECT ENAME, DEPTNO FROM EMP) E;

-- 表连接与子查询
SELECT * FROM DEPT D, (SELECT ENAME, SAL, DEPTNO FROM EMP) E WHERE D.DEPTNO = E.DEPTNO;
