-- 1.WITH短句的应用
WITH 临时别名1 AS
 (子查询),
临时别名2 AS
 (子查询),
.. . 临时别名N AS
 (子查询)
SELECT .. . FROM 临时别名 .. .;

-- 案例1
WITH TMP1 AS
 (SELECT EMPNO, ENAME, DEPTNO FROM EMP)
SELECT * FROM TMP1;

-- 案例2
WITH E AS
 (SELECT EMPNO, ENAME, DEPTNO FROM EMP WHERE DEPTNO = 10)
SELECT * FROM E;

-- 案例3

WITH E AS
 (SELECT * FROM EMP WHERE DEPTNO = 20),
D AS
 (SELECT * FROM DEPT)
SELECT * FROM E JOIN D ON E.DEPTNO = D.DEPTNO;
