-- 查询表
CREATE TABLE EE AS SELECT * FROM E WHERE 1=0;
CREATE TABLE EE_20 AS SELECT * FROM E WHERE 1=0;
CREATE TABLE EE_30 AS SELECT * FROM E WHERE 1=0;
SELECT * FROM EE;
SELECT * FROM EE_20;
SELECT * FROM EE_30;

-- 清空表数据
TRUNCATE TABLE EE;
TRUNCATE TABLE EE_20;
TRUNCATE TABLE EE_30;

-- 3.INSERT FIRST批量插入基本用法与INSERT ALL一致
-- 验证：INSERT FIRST WHEN结构与INSERT ALL WHEN结构区别
INSERT FIRST
    WHEN DEPTNO <20 THEN INTO EE 
    WHEN DEPTNO <30 THEN INTO EE_20
    ELSE INTO EE_30
SELECT 
    E.ENAME, 
    E.SAL, 
    E.DEPTNO, 
    D.DNAME 
FROM 
    EMP E
    JOIN DEPT D ON E.DEPTNO = D.DEPTNO;


---
INSERT ALL
    WHEN DEPTNO <20 THEN INTO EE 
    WHEN DEPTNO <30 THEN INTO EE_20
    ELSE INTO EE_30
SELECT 
    E.ENAME, 
    E.SAL, 
    E.DEPTNO, 
    D.DNAME 
FROM 
    EMP E
    JOIN DEPT D ON E.DEPTNO = D.DEPTNO;
    

-- 删除表
DROP TABLE ee;
DROP TABLE ee_20;
DROP TABLE ee_30;
DROP TABLE my_emp;
DROP TABLE e;
